name: Build Debian ISO with KnowledgeBox Containers

on:
  push:
    branches: [ main ]

env:
  KIWIX_CONTENT_URLS: |
    https://download.kiwix.org/zim/wikipedia/wikipedia_en_for_schools_nopic_2024-08.zim

jobs:
  build-debian-iso:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y live-build docker.io docker-compose git apparmor

    - name: Clone KnowledgeBox repository and build (+ save) container images
      run: |
        git clone https://github.com/TechnologyWithoutBorders/TwB-Knowledge-Box
        cd TwB-Knowledge-Box
        sudo docker-compose build && sudo docker-compose pull
        sudo ../export_all_docker_images.sh

    - name: Add Kiwix content
      run: |
        cd TwB-Knowledge-Box/kiwix/content
        for url in $KIWIX_CONTENT_URLS; do
          wget "$url"
        done

    - name: Set up build directory
      run: |
        mkdir debian-live
        cd debian-live
        lb config \
          --distribution bookworm \
          --debian-installer live \
          --debian-installer-gui true \
          --archive-areas "main contrib non-free non-free-firmware" \
          --bootappend-live "boot=live components username=user hostname=debian"
        echo "task-xfce-desktop docker.io docker-compose" >> config/package-lists/knobo.list.chroot

    - name: Add container images and systemd files
      run: |
        mkdir -p debian-live/config/includes.chroot/root/
        sudo cp -r TwB-Knowledge-Box debian-live/config/includes.chroot/root/
        mkdir -p debian-live/config/includes.chroot/etc/systemd/system/
        sudo cp ./knobo-containers.service debian-live/config/includes.chroot/etc/systemd/system/
        # Enable the service via symlink
        mkdir -p debian-live/config/includes.chroot/etc/systemd/system/multi-user.target.wants
        ln -s /etc/systemd/system/knobo-containers.service debian-live/config/includes.chroot/etc/systemd/system/multi-user.target.wants/knobo-containers.service

    - name: Build ISO
      run: |
        cd debian-live
        sudo lb build

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: custom-debian-iso
        path: debian-live/live-image-amd64.hybrid.iso
